PR/redux login
metagamehub/MGH-APP-V2.0 pull request #224
Opened 2023-06-28 16:53 UTC by Alonsso

Check commit description for detail information

2023-07-06 18:40 UTC, nanSer0 commented
@Alonsso add "s" at the end of "component" folder name

2023-07-20 01:58 UTC, nanSer0 submitted a review, later dismissed
Make changes based on comments on the meet

2023-08-04 04:08 UTC, OswaldUnity requested changes
Lots of things to do, sadly not much time

2023-08-04 04:08 UTC, OswaldUnity commented on package.json
> +    "@arcana/auth-wagmi": "^2.0.0-beta.1",
Please move the packages that you know you are using at the start of the dependencies array, that way we know which ones we need.

2023-08-04 04:08 UTC, OswaldUnity commented on package.json
> +    "@rainbow-me/rainbowkit-siwe-next-auth": "^0.2.0",
If you are not using this packages please remove them.

2023-08-04 04:08 UTC, OswaldUnity commented on src/backend/services/AuthService.ts
> +    nonce: number
interfaces have semicolons at the end of every property

2023-08-04 04:08 UTC, OswaldUnity commented on src/backend/services/AuthService.ts
> +interface nonceResponse {
Interface names follow PascalCase

2023-08-04 04:08 UTC, OswaldUnity commented on src/backend/services/AuthService.ts
> +        const nonceRes = await fetch(
Since we are using axios, try to avoid fetch

2023-08-04 04:08 UTC, OswaldUnity commented on src/backend/services/ITRMService.ts
> +  [key: string]: CoinValue;
this type is called a Record

2023-08-04 04:08 UTC, OswaldUnity commented on src/backend/services/AuthService.ts
> +class AuthService {
Try to avoid classes and move the different methods to functions

2023-08-04 04:08 UTC, OswaldUnity commented on src/backend/services/ITRMService.ts
> +    "decentraland": {
move the keys to an enum

2023-08-04 04:08 UTC, OswaldUnity commented on src/backend/useToken.ts
> +export const axiosBase = axios.create({
Remove export when no one outside of this file is using it

2023-08-04 04:08 UTC, OswaldUnity commented on src/component/login.component..tsx
> +import React, { useState, useEffect, useCallback } from 'react'
avoid importing React from 'react'

2023-08-04 04:08 UTC, OswaldUnity commented on src/component/login.component..tsx
> +import * as loginActions from '../state/loginSlice'
Avoid * on imports

2023-08-04 04:08 UTC, OswaldUnity commented on src/component/login.component..tsx
> +let didSignerSet = false;
component level variables start with "_"

2023-08-04 04:08 UTC, OswaldUnity commented on src/component/login.component..tsx
> +export function Login() {
"export default" for components

2023-08-04 04:08 UTC, OswaldUnity commented on src/backend/useTokenExpiration.ts
Follow file name nomenclature, files should have functionality (goal) name plus "." plus type of file
Example:
Component Hello
Filename should be "hello.component.ext"

2023-08-04 04:08 UTC, OswaldUnity commented on src/backend/useToken.ts
Follow file name nomenclature, files should have functionality (goal) name plus "." plus type of file
Example:
Component Hello
Filename should be "hello.component.ext"

2023-08-04 04:08 UTC, OswaldUnity commented on src/backend/services/ITRMService.ts
This services won't execute on backend

2023-08-04 04:08 UTC, OswaldUnity commented on src/enums/logging.enum.ts
> +  PortfolioSlice = 'PortfolioSliceFetch',
Use values that actually describe the module, in this case this is a redux slice (I don't understand the fetch use here)

2023-08-04 04:08 UTC, OswaldUnity commented on src/enums/logging.enum.ts
> +  WagmiConfig = 'WagmiConfig',
This is wrong as well, doesn't represent where the error is happening

2023-08-04 04:08 UTC, OswaldUnity commented on src/interfaces/common.interface.ts
> +    "decentraland": object,
Avoid the usage of object please

2023-08-04 04:08 UTC, OswaldUnity commented on src/lib/chains.ts
> +export const Chains = {
Needs to have a type please

2023-08-04 04:08 UTC, OswaldUnity commented on src/lib/contracts.ts
> +export const Contracts = {
Needs to have a type please

2023-08-04 04:08 UTC, OswaldUnity commented on src/lib/enums.ts
> +export enum Network {
Enum properties PascalCase please

2023-08-04 04:08 UTC, OswaldUnity commented on src/lib/enums.ts
Move or rename file with a more related name

2023-08-04 04:08 UTC, OswaldUnity commented on src/lib/nftUtils.ts
> +  let contracts: {
Needs to have a type please

2023-08-04 04:08 UTC, OswaldUnity commented on src/lib/nftUtils.ts
> +  providerChainName: 'Ethereum' | 'Polygon' = 'Ethereum',
Create type apart (preferably an enum)

2023-08-04 04:08 UTC, OswaldUnity commented on src/lib/types.ts
> +  name: string
Interface properties end with a semicolon

2023-08-04 04:08 UTC, OswaldUnity commented on src/lib/types.ts
Interfaces should be on an interface folder

2023-08-04 04:08 UTC, OswaldUnity commented on src/lib/utilities.ts
> +export function typedKeys<O extends object, K extends keyof O = keyof O>(
Avoid at all costs

2023-08-04 04:08 UTC, merged