Pr/create new analytics view
metagamehub/MGH-APP-V2.0 pull request #232
Opened 2023-07-27 16:28 UTC by andgonzalezcas

"Updated analytics charts component:

- Added enums and interfaces for better data organization.
- Refactored code to separate functional view and UI components.
- Utilized 'react_redux' for managing application currencies.
- Improved folder structure to enhance code organization.

These changes aim to enhance the analytics charts functionality, improve maintainability, and promote code reusability. The updates allow for easier management of currencies, better separation of concerns, and more straightforward navigation of the project structure.

2023-07-31 14:01 UTC, nanSer0 commented
Fix styles from figma

2023-07-31 14:01 UTC, nanSer0 requested changes
update styles from figma

2023-08-01 21:55 UTC, nanSer0 requested changes

2023-08-01 21:55 UTC, nanSer0 commented on src/app/layout.tsx
> +const fontIcons = FontIcons({ src: '../../public/fonts/fonts-icons/iconSet01.ttf', display: 'block', variable: '--icons-font' })
add semicolon

2023-08-01 21:55 UTC, nanSer0 commented on src/app/layout.tsx
>    const pathname = usePathname()
add semicolon

2023-08-01 21:55 UTC, nanSer0 commented on src/app/layout.tsx
> +  }, [pathname, isConnected])
we should review it with @smarquezmgh

2023-08-01 21:55 UTC, nanSer0 commented on src/app/layout.tsx
> +      if (currencyData) { store.dispatch(setCurrencyValues(currencyData)); }
remove '{' and '}'

2023-08-01 21:55 UTC, nanSer0 commented on src/state/store.ts
> +import { configureStore } from '@reduxjs/toolkit'
add semicolon

2023-08-01 21:55 UTC, nanSer0 commented on src/ui/analytics/chart/chartGridSelector.ui.tsx
> +          alt="button to change charts grid to 2 cols" // Alternate text for accessibility
maybe we don't need this deep comments!

2023-08-01 21:55 UTC, nanSer0 commented on src/ui/analytics/chart/chartNameFilterSelector.ui.tsx
> +};
Create a new file for it

2023-08-01 21:55 UTC, nanSer0 commented on src/ui/analytics/chart/linearChart.ui.tsx
> +//* Main component for the linear chart.
this comment doesn't add util info to component (maybe you want mark the main component, it is not necessary becouse you should have the components on differents files)

2023-08-01 21:55 UTC, nanSer0 commented on src/ui/analytics/chart/linearChart.ui.tsx
> +  }, [chartOptions, currencyData]);
we can review it deeply

2023-08-08 20:58 UTC, nanSer0 requested changes

2023-08-08 20:58 UTC, nanSer0 commented on src/ui/analytics/chart/filterNameOption.tsx
> +import { useState } from "react";
this component doesn't have the correct name, it should be named ........   .ui.tsx

2023-08-09 16:39 UTC, nanSer0 approved these changes

2023-08-15 18:45 UTC, OswaldUnity commented
Please fix conflict first

2023-08-16 14:11 UTC, merged