portfolio and watchlist view added
metagamehub/MGH-APP-V2.0 pull request #234
Opened 2023-08-01 18:22 UTC by smarquezmgh

portfolioUI and watchlistUI added

2023-08-01 19:22 UTC, nanSer0 requested changes

2023-08-01 19:22 UTC, nanSer0 commented on src/app/metaverseexplorer/page.tsx
> +import HeatmapComponent from "../../component/heatmap/heatmap.component"
add semicolon to the end line

2023-08-01 19:22 UTC, nanSer0 commented on src/app/metaverseexplorer/watchlist/page.tsx
> +import WatchlistComponent from "../../../component/watchlist/watchlist.component"
add semicolon to the end line

2023-08-01 19:22 UTC, nanSer0 commented on src/component/heatmap/heatmap.component.tsx
> +import IsLoginUI from "../../ui/common/isLogin.ui"
add semicolon to the end line

2023-08-01 19:22 UTC, nanSer0 commented on src/component/portfolio/portfolio.component.tsx
> +const ivalue = 1.52
add semicolon to the end line

2023-08-01 19:22 UTC, nanSer0 commented on src/component/portfolio/portfolio.component.tsx
> +  const [isEmpty, setIsEmpty] = useState<boolean>(false)
add semicolon to the end line

2023-08-01 19:22 UTC, nanSer0 commented on src/component/portfolio/portfolio.component.tsx
> +    setLandsOwned(ilands.length)
add semicolon to the end line

2023-08-01 19:22 UTC, nanSer0 commented on src/component/portfolio/portfolio.component.tsx
> +        setIsEmpty(false)
add semicolon to the end line

2023-08-01 19:22 UTC, nanSer0 commented on src/component/portfolio/portfolio.component.tsx
> +        setIsEmpty(false)
add semicolon to the end line

2023-08-01 19:22 UTC, nanSer0 commented on src/component/portfolio/portfolio.component.tsx
> +        setIsEmpty(true)
add semicolon to the end line

2023-08-01 19:22 UTC, nanSer0 commented on src/component/portfolio/portfolio.component.tsx
> +  const isConnected = true
this const changes the UI, it should be a useState or similar

2023-08-01 19:22 UTC, nanSer0 commented on src/component/portfolio/portfolio.component.tsx
> +        </>
make a portfolio UI component for that

2023-08-01 19:22 UTC, nanSer0 commented on src/component/watchlist/watchlist.component.tsx
> +  const isConnected = true
this const changes the UI, it should be a useState or similar

2023-08-01 19:22 UTC, nanSer0 commented on src/component/watchlist/watchlist.component.tsx
> +  const isConnected = true
and add semicolon to the end line

2023-08-01 19:22 UTC, nanSer0 commented on src/component/watchlist/watchlist.component.tsx
> +        </>
meake a watchlist UI component for that

2023-08-01 19:22 UTC, nanSer0 commented on src/types/valuationTypes.ts
> +  'somnium-space-cubes': number
add semicolons

2023-08-01 19:22 UTC, nanSer0 commented on src/types/valuationTypes.ts
> +export type LandListAPIResponse = Record<string, LandProps>
add semicolon to end line

2023-08-01 19:22 UTC, nanSer0 commented on src/ui/common/externalAssetsLink.ui.tsx
> +import { LandProps } from '../../types/valuationTypes'
add semicolon to end line

2023-08-01 19:22 UTC, nanSer0 commented on src/ui/common/externalAssetsLink.ui.tsx
> +  isOpen: boolean
add semicolon to end line

2023-08-01 19:22 UTC, nanSer0 commented on src/ui/common/externalLink.ui.tsx
> +  externalLink: string
add semicolon to end line

2023-08-01 19:22 UTC, nanSer0 commented on src/ui/common/informationCard.ui.tsx
> +import { ICoinPrices, LandProps } from "../../types/valuationTypes"
add semicolon to end line

2023-08-01 19:22 UTC, nanSer0 commented on src/ui/common/informationCard.ui.tsx
> +    prices: ICoinPrices
add semicolon to end line

2023-08-01 19:22 UTC, nanSer0 commented on src/ui/common/informationCard.ui.tsx
> +    const closeModal = () => setModalOpen(false);
maybe you can use the set function directly

2023-08-01 19:22 UTC, nanSer0 commented on src/ui/common/landCard.ui.tsx
> +  prices: ICoinPrices
add semicolon to the end line

2023-08-01 19:22 UTC, nanSer0 commented on src/ui/common/priceList.ui.tsx
> +    prices: ICoinPrices
add semicolon to end line

2023-08-01 19:22 UTC, nanSer0 commented on src/ui/common/priceList.ui.tsx
> +import { ICoinPrices } from "../../types/valuationTypes"
add semicolon to end line

2023-08-01 19:22 UTC, nanSer0 commented on src/ui/common/specificInformationCard.ui.tsx
> +import { ICoinPrices, LandProps } from "../../types/valuationTypes"
add semicolon to end line

2023-08-01 19:22 UTC, nanSer0 commented on src/ui/common/specificInformationCard.ui.tsx
> +  prices: ICoinPrices
add semicolon to end line

2023-08-01 19:22 UTC, nanSer0 commented on src/ui/common/specificLandModal.ui.tsx
> +  prices: ICoinPrices
add semicolon to end line

2023-08-01 19:22 UTC, nanSer0 commented on src/ui/common/specificPriceList.ui.tsx
> +import { ICoinPrices } from "../../types/valuationTypes"
add semicolon to end line

2023-08-01 19:22 UTC, nanSer0 commented on src/ui/common/specificPriceList.ui.tsx
> +  prices: ICoinPrices
add semicolon to end line

2023-08-01 19:22 UTC, nanSer0 commented on src/ui/portfolio/landsMenu.ui.tsx
> +  isWatchlist: boolean,
add semicolon to end line

2023-08-01 19:22 UTC, nanSer0 commented on src/ui/watchlist/searchByCoords.ui.tsx
> +import { Metaverses } from "../../enums/enums"
add semicolon to end line

2023-08-01 19:22 UTC, nanSer0 commented on src/ui/watchlist/searchByCoords.ui.tsx
> +  metaverse: Metaverses;
add semicolon to end line

2023-08-01 19:22 UTC, nanSer0 commented on src/ui/watchlist/searchById.ui.tsx
> +import { Metaverses } from "../../enums/enums"
add semicolon to end line

2023-08-01 19:22 UTC, nanSer0 commented on src/ui/watchlist/searchById.ui.tsx
> +  metaverse: Metaverses;
add semicolon to end line

2023-08-01 19:22 UTC, nanSer0 commented on src/ui/watchlist/searchById.ui.tsx
> +            setTokenId(input.target.value)
input doesn't represent the property, 'event' or 'e' represents the real variable

2023-08-01 19:22 UTC, nanSer0 commented on src/ui/watchlist/serchLandForm.ui.tsx
> +  land?: LandProps
add semicolon to end line

2023-08-01 19:22 UTC, nanSer0 commented on src/utils/metaverse.ts
> +  export type Metaverse = keyof typeof metaverseObject
add semicolon to end line

2023-08-01 19:22 UTC, nanSer0 commented on src/component/portfolio/portfolio.component.tsx
> +  const [metaverse, setMetaverse] = useState(Metaverses.ALL)
add type

2023-08-01 19:22 UTC, nanSer0 commented on src/component/watchlist/watchlist.component.tsx
> +  const [metaverse, setMetaverse] = useState(Metaverses.ALL)
add type

2023-08-01 19:22 UTC, nanSer0 commented on src/ui/common/informationCard.ui.tsx
> +    const [isModalOpen, setModalOpen] = useState(false);
add type

2023-08-01 19:22 UTC, nanSer0 commented on src/ui/watchlist/searchByCoords.ui.tsx
> +  const [y, setY] = useState<number>();
initialize with a value

2023-08-01 23:30 UTC, smarquezmgh commented on src/component/portfolio/portfolio.component.tsx
> +const ivalue = 1.52
emicolon cannot be used because it is an data object

2023-08-01 23:32 UTC, smarquezmgh commented on src/component/portfolio/portfolio.component.tsx
> +  const isConnected = true
this variable will be set when connected to the login state redux variable

2023-08-03 00:30 UTC, nanSer0 approved these changes

2023-08-04 04:09 UTC, OswaldUnity commented
Fix conflicts first please

2023-08-08 20:55 UTC, merged