portfolio and watchlist functionality
metagamehub/MGH-APP-V2.0 pull request #244
Opened 2023-08-24 23:43 UTC by smarquezmgh

- redux state added into portfolio component and watchlist component
- to many changes with enums call and enums files
- multiple changes in portfolio components(UI) for functional integration

2023-08-28 15:27 UTC, nanSer0 requested changes
This branch has conflicts that must be resolved

2023-08-29 16:36 UTC, nanSer0 approved these changes

2023-08-31 03:27 UTC, OswaldUnity commented
This branch has conflicts that must be resolved

2023-08-31 03:30 UTC, OswaldUnity commented on src/ui/common/landsMenu.ui.tsx
> +            {(Object.keys(MetaverseOptions) as Array<keyof typeof MetaverseOptions>).map((key) => {
Last time you created a type for this

2023-08-31 03:30 UTC, OswaldUnity commented on src/ui/common/landsMenu.ui.tsx
> +            {typedKeys(MetaverseOptions).map((key) => {
Last time you created a type for this

2023-08-31 19:24 UTC, nanSer0 requested changes
adjust comments and conflicts

2023-09-01 18:53 UTC, merged