watchlist (redux) state added
metagamehub/MGH-APP-V2.0 pull request #247
Opened 2023-09-01 14:58 UTC by smarquezmgh

2023-09-04 18:14 UTC, nanSer0 requested changes

2023-09-04 18:14 UTC, nanSer0 commented on src/ui/common/externalAssetsLink.ui.tsx
> +        {metaverse === "somnium-space" && <Image src='/images/somnium-space-logo.png' width={55} height={55} alt='somniun-space' className='rounded-full p-2 bg-nm-highlight absolute bottom-3 left-3'
use enum for that

2023-09-04 18:14 UTC, nanSer0 commented on src/ui/common/landsMenu.ui.tsx
> +            {(Object.keys(MetaverseOptions) as Array<MetaverseOptionsKey>).map((key) => {
we have a util for Object.keys

2023-09-04 18:14 UTC, nanSer0 commented on src/ui/common/landsMenu.ui.tsx
> +            {(Object.keys(MetaverseOptions) as Array<MetaverseOptionsKey>).map((key) => {
we have a util for Object.keys

2023-09-04 18:14 UTC, nanSer0 commented on src/ui/heatmap/hotDeals/hotDealsCard.ui.tsx
> +    if (metaverseSelected == "somnium-space") return '/images/somnium-space-cube-logo.webp';
use enum for that

2023-09-05 23:35 UTC, nanSer0 approved these changes

2023-09-06 03:55 UTC, merged

2023-09-06 03:58 UTC, OswaldUnity commented
Please fix the linter errors @smarquezmgh @nanSer0